config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :posts
  resources :comments
  root "posts#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

 
  
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_rich_text :post
    validates :post, presence: true

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  # before_action :check_user?,only: %i[update edit destroy]

  # GET /posts or /posts.json
  def index
    @post = Post.paginate(:page=>params[:page],per_page:5)


  
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit

  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        # user =Hash.new(:name => "saran",:email => "sraj67487@gmail.com")
      
        UserMailer.with(user: User.find_by(id: current_user.id)).welcome_email.deliver_later
        
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:post,:user_id)
    end
    def check_user?
       if(current_user.id== @post.user_id)
         return true
       else
        return false
       end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :post, style: "display: block" %>
   
    
    <%= form.rich_text_area :post, class:"input-post"%>

    <%= form.text_field :user_id, id: :post_user_id,type: :hidden,  value:current_user.id %>
  </div>

  <div>
    <%= form.submit "create post", class:"btn btn-info px-2 py-2 mt-5" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div  class=" post mt-5 pt-5 " id="<%= dom_id post %>">


    

 
 <p class="display-4 fw-bolder text-info " ><%=  User.find_by(id: post.user_id).name%></p> 


    
   <p class="display-3"> <%= post.post %></p>

    Posted on<span class="display-5 text-success">
 <%= post.created_at%>
  
 
</span>
<div class="display-6"><%= render 'comment/index', post: post.id %></div>
<p class="text-center"><%= render 'comment/new', post_val: post.id %>
</p>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>



<div class=" post-par" id="posts">
  <% @post.each do |post| %>
  <div class="post-p"> <%= render post %>
      <%= link_to "Show this post", post, class:"btn btn-info" %>  
   </div>
  <% end %>
<%= will_paginate @post,renderer: BootstrapPagination::Rails %>
</div>

app/views/posts/new.html.erb
<div class="post post-par center mr-5"><h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
 <%if(current_user.id==@post.user_id)%> 
  <%= link_to "Edit this post", edit_post_path(@post) %> 
  <%= button_to "Destroy this post", @post, method: :delete %>
  
 <%end%> 


  <%= link_to "Back to posts", posts_path %>

  
</div>